### ISSUE TITLE
frog for Vodafone TV Solution customers

### ISSUE THREAD

**Issue by joemerlino** [frogbywyplay/utils_frog-packages#1]
Hi, i'm sorry to open an issue for this, but thousands of Vodafone customers wants to update their "Tv solutions" with Frog or one other firmware, can you help us? Vodafone killed the product and we have all this great set top boxes with an old firmware on it with limited functionality.
Thanks in advance and sorry for my bad english!

**Comment by gensuque** [comment]
Hi Joe
Don't apologise for your english, it might actually be better than mine ;)
Frog is only available to our licensee companies and runs on a range of reference hardware, but not on the Vodafone hardware.
See: https://frogbywyplay.com/solution/frog-ref-implementations/ 
I am afraid we cannot be of any help

**Comment by joemerlino** [comment]
Oh okay i see..So i think you can't do nothing with this. Can you at least suggest vodafone to open up their firmware? thanks for your support anyway!
